credentials = 'cookies'
required = 'session__id'

[api]
episodes = '{url}?token={token}&direction=asc&with_upcoming=true&sort=number&blocked=true&page=1&per_page=100&app=100000a'
videos = 'https://www.viki.com/api/videos/{video_id}'

[vmplayer]
version = '14.10.0' # x-viki-app-ver
